// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.25.3
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MissionInvitedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FatherUserId string `protobuf:"bytes,1,opt,name=father_user_id,json=fatherUserId,proto3" json:"father_user_id"`
	Twitter      string `protobuf:"bytes,2,opt,name=twitter,proto3" json:"twitter"`
}

func (x *MissionInvitedReq) Reset() {
	*x = MissionInvitedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissionInvitedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionInvitedReq) ProtoMessage() {}

func (x *MissionInvitedReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionInvitedReq.ProtoReflect.Descriptor instead.
func (*MissionInvitedReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *MissionInvitedReq) GetFatherUserId() string {
	if x != nil {
		return x.FatherUserId
	}
	return ""
}

func (x *MissionInvitedReq) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

type MissionTweetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	TweetId string `protobuf:"bytes,2,opt,name=tweet_id,json=tweetId,proto3" json:"tweet_id"`
}

func (x *MissionTweetReq) Reset() {
	*x = MissionTweetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissionTweetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionTweetReq) ProtoMessage() {}

func (x *MissionTweetReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionTweetReq.ProtoReflect.Descriptor instead.
func (*MissionTweetReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *MissionTweetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MissionTweetReq) GetTweetId() string {
	if x != nil {
		return x.TweetId
	}
	return ""
}

type ScoreListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	PageNo    int64  `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no"`
	PageSize  int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	ScoreType uint64 `protobuf:"varint,4,opt,name=score_type,json=scoreType,proto3" json:"score_type"`
}

func (x *ScoreListReq) Reset() {
	*x = ScoreListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreListReq) ProtoMessage() {}

func (x *ScoreListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreListReq.ProtoReflect.Descriptor instead.
func (*ScoreListReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *ScoreListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ScoreListReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ScoreListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ScoreListReq) GetScoreType() uint64 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

type ConsumeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	PageNo      int64  `protobuf:"varint,2,opt,name=page_no,json=pageNo,proto3" json:"page_no"`
	PageSize    int64  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size"`
	ConsumeType uint64 `protobuf:"varint,4,opt,name=consume_type,json=consumeType,proto3" json:"consume_type"`
}

func (x *ConsumeListReq) Reset() {
	*x = ConsumeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeListReq) ProtoMessage() {}

func (x *ConsumeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeListReq.ProtoReflect.Descriptor instead.
func (*ConsumeListReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *ConsumeListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConsumeListReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ConsumeListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ConsumeListReq) GetConsumeType() uint64 {
	if x != nil {
		return x.ConsumeType
	}
	return 0
}

type ScoreDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Score      int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score"`
	Desc       string `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc"`
	CreateTime int64  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time"`
}

func (x *ScoreDetail) Reset() {
	*x = ScoreDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreDetail) ProtoMessage() {}

func (x *ScoreDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreDetail.ProtoReflect.Descriptor instead.
func (*ScoreDetail) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoreDetail) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreDetail) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ScoreDetail) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ScoreListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentScore  uint64         `protobuf:"varint,1,opt,name=current_score,json=currentScore,proto3" json:"current_score"`
	ScoreAccuracy uint64         `protobuf:"varint,2,opt,name=score_accuracy,json=scoreAccuracy,proto3" json:"score_accuracy"`
	Score         []*ScoreDetail `protobuf:"bytes,3,rep,name=score,proto3" json:"score"`
}

func (x *ScoreListResp) Reset() {
	*x = ScoreListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScoreListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreListResp) ProtoMessage() {}

func (x *ScoreListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreListResp.ProtoReflect.Descriptor instead.
func (*ScoreListResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreListResp) GetCurrentScore() uint64 {
	if x != nil {
		return x.CurrentScore
	}
	return 0
}

func (x *ScoreListResp) GetScoreAccuracy() uint64 {
	if x != nil {
		return x.ScoreAccuracy
	}
	return 0
}

func (x *ScoreListResp) GetScore() []*ScoreDetail {
	if x != nil {
		return x.Score
	}
	return nil
}

type ConsumeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentConsume uint64         `protobuf:"varint,1,opt,name=current_consume,json=currentConsume,proto3" json:"current_consume"`
	ScoreAccuracy  uint64         `protobuf:"varint,2,opt,name=score_accuracy,json=scoreAccuracy,proto3" json:"score_accuracy"`
	Score          []*ScoreDetail `protobuf:"bytes,3,rep,name=score,proto3" json:"score"`
}

func (x *ConsumeListResp) Reset() {
	*x = ConsumeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeListResp) ProtoMessage() {}

func (x *ConsumeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeListResp.ProtoReflect.Descriptor instead.
func (*ConsumeListResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *ConsumeListResp) GetCurrentConsume() uint64 {
	if x != nil {
		return x.CurrentConsume
	}
	return 0
}

func (x *ConsumeListResp) GetScoreAccuracy() uint64 {
	if x != nil {
		return x.ScoreAccuracy
	}
	return 0
}

func (x *ConsumeListResp) GetScore() []*ScoreDetail {
	if x != nil {
		return x.Score
	}
	return nil
}

type MissionProfileResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Score     uint64 `protobuf:"varint,2,opt,name=score,proto3" json:"score"`
	ScoreUsed uint64 `protobuf:"varint,3,opt,name=score_used,json=scoreUsed,proto3" json:"score_used"`
	Cash      uint64 `protobuf:"varint,4,opt,name=cash,proto3" json:"cash"`
}

func (x *MissionProfileResp) Reset() {
	*x = MissionProfileResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MissionProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionProfileResp) ProtoMessage() {}

func (x *MissionProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionProfileResp.ProtoReflect.Descriptor instead.
func (*MissionProfileResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *MissionProfileResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MissionProfileResp) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MissionProfileResp) GetScoreUsed() uint64 {
	if x != nil {
		return x.ScoreUsed
	}
	return 0
}

func (x *MissionProfileResp) GetCash() uint64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

type Consume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Desc          string         `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc"`
	DescId        string         `protobuf:"bytes,3,opt,name=desc_id,json=descId,proto3" json:"desc_id"`
	ScoreAccuracy uint64         `protobuf:"varint,4,opt,name=score_accuracy,json=scoreAccuracy,proto3" json:"score_accuracy"`
	ScoreType     uint64         `protobuf:"varint,5,opt,name=score_type,json=scoreType,proto3" json:"score_type"`
	ScoreAmount   uint64         `protobuf:"varint,6,opt,name=score_amount,json=scoreAmount,proto3" json:"score_amount"`
	ScoreHistory  []*ScoreDetail `protobuf:"bytes,8,rep,name=score_history,json=scoreHistory,proto3" json:"score_history"`
}

func (x *Consume) Reset() {
	*x = Consume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Consume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consume) ProtoMessage() {}

func (x *Consume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consume.ProtoReflect.Descriptor instead.
func (*Consume) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *Consume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Consume) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Consume) GetDescId() string {
	if x != nil {
		return x.DescId
	}
	return ""
}

func (x *Consume) GetScoreAccuracy() uint64 {
	if x != nil {
		return x.ScoreAccuracy
	}
	return 0
}

func (x *Consume) GetScoreType() uint64 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *Consume) GetScoreAmount() uint64 {
	if x != nil {
		return x.ScoreAmount
	}
	return 0
}

func (x *Consume) GetScoreHistory() []*ScoreDetail {
	if x != nil {
		return x.ScoreHistory
	}
	return nil
}

type Mission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Desc          string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc"`
	ScoreAccuracy uint64 `protobuf:"varint,3,opt,name=score_accuracy,json=scoreAccuracy,proto3" json:"score_accuracy"`
	ScoreType     uint64 `protobuf:"varint,4,opt,name=score_type,json=scoreType,proto3" json:"score_type"`
	ScoreAmount   uint64 `protobuf:"varint,5,opt,name=score_amount,json=scoreAmount,proto3" json:"score_amount"`
	Daily         bool   `protobuf:"varint,6,opt,name=daily,proto3" json:"daily"`
	Undo          bool   `protobuf:"varint,7,opt,name=undo,proto3" json:"undo"`
	MissionScore  uint64 `protobuf:"varint,8,opt,name=mission_score,json=missionScore,proto3" json:"mission_score"`
}

func (x *Mission) Reset() {
	*x = Mission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mission) ProtoMessage() {}

func (x *Mission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mission.ProtoReflect.Descriptor instead.
func (*Mission) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *Mission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Mission) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Mission) GetScoreAccuracy() uint64 {
	if x != nil {
		return x.ScoreAccuracy
	}
	return 0
}

func (x *Mission) GetScoreType() uint64 {
	if x != nil {
		return x.ScoreType
	}
	return 0
}

func (x *Mission) GetScoreAmount() uint64 {
	if x != nil {
		return x.ScoreAmount
	}
	return 0
}

func (x *Mission) GetDaily() bool {
	if x != nil {
		return x.Daily
	}
	return false
}

func (x *Mission) GetUndo() bool {
	if x != nil {
		return x.Undo
	}
	return false
}

func (x *Mission) GetMissionScore() uint64 {
	if x != nil {
		return x.MissionScore
	}
	return 0
}

type GameGetInviteCodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`
}

func (x *GameGetInviteCodeResp) Reset() {
	*x = GameGetInviteCodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameGetInviteCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetInviteCodeResp) ProtoMessage() {}

func (x *GameGetInviteCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetInviteCodeResp.ProtoReflect.Descriptor instead.
func (*GameGetInviteCodeResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{10}
}

func (x *GameGetInviteCodeResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GameRandomReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Level  uint64 `protobuf:"varint,2,opt,name=level,proto3" json:"level"`
}

func (x *GameRandomReq) Reset() {
	*x = GameRandomReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRandomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRandomReq) ProtoMessage() {}

func (x *GameRandomReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRandomReq.ProtoReflect.Descriptor instead.
func (*GameRandomReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{11}
}

func (x *GameRandomReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameRandomReq) GetLevel() uint64 {
	if x != nil {
		return x.Level
	}
	return 0
}

type GameRandomResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dice1 uint64 `protobuf:"varint,1,opt,name=dice1,proto3" json:"dice1"`
	Dice2 uint64 `protobuf:"varint,2,opt,name=dice2,proto3" json:"dice2"`
	Cash  uint64 `protobuf:"varint,3,opt,name=cash,proto3" json:"cash"`
}

func (x *GameRandomResp) Reset() {
	*x = GameRandomResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameRandomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRandomResp) ProtoMessage() {}

func (x *GameRandomResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRandomResp.ProtoReflect.Descriptor instead.
func (*GameRandomResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{12}
}

func (x *GameRandomResp) GetDice1() uint64 {
	if x != nil {
		return x.Dice1
	}
	return 0
}

func (x *GameRandomResp) GetDice2() uint64 {
	if x != nil {
		return x.Dice2
	}
	return 0
}

func (x *GameRandomResp) GetCash() uint64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

type LeaderBoardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit"`
}

func (x *LeaderBoardReq) Reset() {
	*x = LeaderBoardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderBoardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderBoardReq) ProtoMessage() {}

func (x *LeaderBoardReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderBoardReq.ProtoReflect.Descriptor instead.
func (*LeaderBoardReq) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{13}
}

func (x *LeaderBoardReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LeaderBoardReq) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderBoardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*LeaderBoardResp_LeaderBoardItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items"`
	Self  *LeaderBoardResp_LeaderBoardItem   `protobuf:"bytes,2,opt,name=self,proto3" json:"self"`
}

func (x *LeaderBoardResp) Reset() {
	*x = LeaderBoardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderBoardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderBoardResp) ProtoMessage() {}

func (x *LeaderBoardResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderBoardResp.ProtoReflect.Descriptor instead.
func (*LeaderBoardResp) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{14}
}

func (x *LeaderBoardResp) GetItems() []*LeaderBoardResp_LeaderBoardItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *LeaderBoardResp) GetSelf() *LeaderBoardResp_LeaderBoardItem {
	if x != nil {
		return x.Self
	}
	return nil
}

type LeaderBoardResp_LeaderBoardItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wallet string `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet"`
	Cash   uint64 `protobuf:"varint,2,opt,name=cash,proto3" json:"cash"`
	Rank   uint64 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank"`
}

func (x *LeaderBoardResp_LeaderBoardItem) Reset() {
	*x = LeaderBoardResp_LeaderBoardItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaderBoardResp_LeaderBoardItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderBoardResp_LeaderBoardItem) ProtoMessage() {}

func (x *LeaderBoardResp_LeaderBoardItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderBoardResp_LeaderBoardItem.ProtoReflect.Descriptor instead.
func (*LeaderBoardResp_LeaderBoardItem) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{14, 0}
}

func (x *LeaderBoardResp_LeaderBoardItem) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *LeaderBoardResp_LeaderBoardItem) GetCash() uint64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *LeaderBoardResp_LeaderBoardItem) GetRank() uint64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

var File_proto_game_proto protoreflect.FileDescriptor

var file_proto_game_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x11, 0x4d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x12, 0x24, 0x0a, 0x0e, 0x66, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x22, 0x3c, 0x0a, 0x0f, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x77, 0x65, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x77, 0x65, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x77, 0x65, 0x65, 0x74, 0x49, 0x64, 0x22, 0x7c,
	0x0a, 0x0c, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x6f,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x82, 0x01, 0x0a,
	0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x4e,
	0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x68, 0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x85, 0x01, 0x0a, 0x0d,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x75,
	0x72, 0x61, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0x8b, 0x01, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61,
	0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x41,
	0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x22, 0x6d, 0x0a, 0x12, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x55, 0x73, 0x65, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x63, 0x61, 0x73, 0x68,
	0x22, 0xec, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x65, 0x73, 0x63, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x73, 0x63, 0x49, 0x64, 0x12, 0x25, 0x0a,
	0x0e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x63, 0x63, 0x75,
	0x72, 0x61, 0x63, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x37, 0x0a, 0x0d, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x52, 0x0c, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22,
	0xe9, 0x01, 0x0a, 0x07, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x61, 0x63, 0x63,
	0x75, 0x72, 0x61, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x41, 0x63, 0x63, 0x75, 0x72, 0x61, 0x63, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0b, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x64, 0x61, 0x69, 0x6c, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x61, 0x69,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x2b, 0x0a, 0x15, 0x47,
	0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x0d, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x50, 0x0a, 0x0e, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x69,
	0x63, 0x65, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x64, 0x69, 0x63, 0x65, 0x31,
	0x12, 0x14, 0x0a, 0x05, 0x64, 0x69, 0x63, 0x65, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x64, 0x69, 0x63, 0x65, 0x32, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x63, 0x61, 0x73, 0x68, 0x22, 0x3e, 0x0a, 0x0e, 0x4c, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xde, 0x01, 0x0a, 0x0f, 0x4c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x3a, 0x0a, 0x04,
	0x73, 0x65, 0x6c, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x04, 0x73, 0x65, 0x6c, 0x66, 0x1a, 0x51, 0x0a, 0x0f, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x63, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b, 0x32, 0x9b, 0x04, 0x0a, 0x04,
	0x47, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x43, 0x0a, 0x11, 0x47, 0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0b, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x30, 0x0a, 0x0e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x6e, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x34, 0x0a, 0x0c, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54,
	0x77, 0x65, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x77, 0x65, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0e, 0x4d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x64, 0x12, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x76, 0x69,
	0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x0e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x09, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x0b, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData = file_proto_game_proto_rawDesc
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_game_proto_rawDescData)
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_game_proto_goTypes = []interface{}{
	(*MissionInvitedReq)(nil),               // 0: proto.MissionInvitedReq
	(*MissionTweetReq)(nil),                 // 1: proto.MissionTweetReq
	(*ScoreListReq)(nil),                    // 2: proto.ScoreListReq
	(*ConsumeListReq)(nil),                  // 3: proto.ConsumeListReq
	(*ScoreDetail)(nil),                     // 4: proto.ScoreDetail
	(*ScoreListResp)(nil),                   // 5: proto.ScoreListResp
	(*ConsumeListResp)(nil),                 // 6: proto.ConsumeListResp
	(*MissionProfileResp)(nil),              // 7: proto.MissionProfileResp
	(*Consume)(nil),                         // 8: proto.Consume
	(*Mission)(nil),                         // 9: proto.Mission
	(*GameGetInviteCodeResp)(nil),           // 10: proto.GameGetInviteCodeResp
	(*GameRandomReq)(nil),                   // 11: proto.GameRandomReq
	(*GameRandomResp)(nil),                  // 12: proto.GameRandomResp
	(*LeaderBoardReq)(nil),                  // 13: proto.LeaderBoardReq
	(*LeaderBoardResp)(nil),                 // 14: proto.LeaderBoardResp
	(*LeaderBoardResp_LeaderBoardItem)(nil), // 15: proto.LeaderBoardResp.LeaderBoardItem
	(*UserIdReq)(nil),                       // 16: proto.UserIdReq
	(*Empty)(nil),                           // 17: proto.Empty
}
var file_proto_game_proto_depIdxs = []int32{
	4,  // 0: proto.ScoreListResp.score:type_name -> proto.ScoreDetail
	4,  // 1: proto.ConsumeListResp.score:type_name -> proto.ScoreDetail
	4,  // 2: proto.Consume.score_history:type_name -> proto.ScoreDetail
	15, // 3: proto.LeaderBoardResp.items:type_name -> proto.LeaderBoardResp.LeaderBoardItem
	15, // 4: proto.LeaderBoardResp.self:type_name -> proto.LeaderBoardResp.LeaderBoardItem
	11, // 5: proto.Game.GameRandom:input_type -> proto.GameRandomReq
	16, // 6: proto.Game.GameGetInviteCode:input_type -> proto.UserIdReq
	13, // 7: proto.Game.LeaderBoard:input_type -> proto.LeaderBoardReq
	16, // 8: proto.Game.MissionCheckIn:input_type -> proto.UserIdReq
	1,  // 9: proto.Game.MissionTweet:input_type -> proto.MissionTweetReq
	0,  // 10: proto.Game.MissionInvited:input_type -> proto.MissionInvitedReq
	16, // 11: proto.Game.MissionProfile:input_type -> proto.UserIdReq
	2,  // 12: proto.Game.ScoreList:input_type -> proto.ScoreListReq
	3,  // 13: proto.Game.ConsumeList:input_type -> proto.ConsumeListReq
	12, // 14: proto.Game.GameRandom:output_type -> proto.GameRandomResp
	10, // 15: proto.Game.GameGetInviteCode:output_type -> proto.GameGetInviteCodeResp
	14, // 16: proto.Game.LeaderBoard:output_type -> proto.LeaderBoardResp
	17, // 17: proto.Game.MissionCheckIn:output_type -> proto.Empty
	17, // 18: proto.Game.MissionTweet:output_type -> proto.Empty
	17, // 19: proto.Game.MissionInvited:output_type -> proto.Empty
	7,  // 20: proto.Game.MissionProfile:output_type -> proto.MissionProfileResp
	5,  // 21: proto.Game.ScoreList:output_type -> proto.ScoreListResp
	6,  // 22: proto.Game.ConsumeList:output_type -> proto.ConsumeListResp
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissionInvitedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissionTweetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScoreListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MissionProfileResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Consume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameGetInviteCodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRandomReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameRandomResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderBoardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderBoardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaderBoardResp_LeaderBoardItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_rawDesc = nil
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
